name: CI Pipeline

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm test

  upload-docker:
  needs: build-and-test
  if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Set Tag
      id: tag
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "TAG=latest" >> $GITHUB_ENV
        else
          echo "TAG=dev" >> $GITHUB_ENV
        fi

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-app:${{ env.TAG }} .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-app:${{ env.TAG }}
